
# Uploading a Docker image to GCR using Github Actions

- uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  with:
    service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
    project_id: ${{ secrets.PROJECT_ID }}
    export_default_credentials: true

- name: Image
  run: |-
    docker build --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }} -t us.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .

# Configure docker to use the gcloud command-line tool as a credential helper
- run: |
    gcloud auth configure-docker -q

# Push image to Google Container Registry
- name: Build
  run: |-
    docker push us.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA